version: "3.9"

services:
  app:
    # image: vedrouniverse/vedro-cloud-api:0.4.0
    build: .
    environment:
      - TZ=UTC
      - DB_URI=mongodb://vedro_cloud:vedro_cloud@mongo:27017
    ports:
      - "8080:80"
    healthcheck:
      test: "wget -q -O - http://localhost/healthcheck"
      interval: 3s
      timeout: 5s
      retries: 10

  db:
    image: mongo:7.0
    environment:
      - TZ=UTC
      - MONGO_INITDB_ROOT_USERNAME=vedro_cloud
      - MONGO_INITDB_ROOT_PASSWORD=vedro_cloud
      - MONGO_INITDB_DATABASE=vedro_cloud
    volumes:
      - ./mongodata:/data/db
    ports:
      - "27017:27017"
