version: "3.9"

services:
  app:
    image: vedrouniverse/vedro-cloud-api:0.1.0
    environment:
      - TZ=UTC
      - DB_DSN=postgresql://vedro_cloud:vedro_cloud@db:5432/vedro_cloud
    ports:
      - "8080:80"
    healthcheck:
      test: "wget -q -O - http://localhost/healthcheck"
      interval: 3s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    environment:
      - TZ=UTC
      - POSTGRES_USER=vedro_cloud
      - POSTGRES_PASSWORD=vedro_cloud
      - POSTGRES_DB=vedro_cloud
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    healthcheck:
      test: "pg_isready -U vedro_cloud"
      interval: 3s
      timeout: 5s
      retries: 10
